### ISSUE TITLE
Typescript and Node intro on the Rust language page in alphadocs

### ISSUE THREAD

**Issue by nicholastmosher** [getditto/alphadocs#6]
**Describe the issue**

On the new alphadocs "Installing Rust" page, the first line after the title is:

> Ditto supports Web and Node.js based development using the JavaScript and [TypeScript](https://www.typescriptlang.org/) languages.

Additionally, under "Setup", there is a duplication of the Cargo.toml code block that is unformatted and redundant.

**To Reproduce**
1. Docs site link: https://alphadocs.ditto.live/installing-ditto-for-rust
2. Both errors are visible above the scroll

**Expected behavior**

**Screenshots**

![image](https://github.com/getditto/alphadocs/assets/4210949/a8ab009b-327f-4d26-afb8-0997384bb4b0)

**Comment by skylerjokiel** [comment]
Fixed 🔨

Thanks for reporting and the detailed issue!
